FROM hotoku/tidyverse:{{ RSTUDIO_TAG }}

ENV TZ JST-9

RUN \
  sudo apt-get update -y && \
  sudo apt-get install -y --no-install-recommends \
  libcairo2-dev \
  libxt-dev \
  fonts-noto-cjk \
  libc6-dev-i386 && \
  wget -O OpenBUGS-3.2.3.tar.gz "http://www.openbugs.net/w/OpenBUGS_3_2_3?action=AttachFile&do=get&target=OpenBUGS-3.2.3.tar.gz" && \
  tar xzvf OpenBUGS-3.2.3.tar.gz && \
  cd OpenBUGS-3.2.3 && \
  ./configure && \
  make && make install && \
  install2.r -n4 --error --deps TRUE \
  -r https://cran.r-project.org/ \
  BRugs \
  ConfigParser \
  R2OpenBUGS \
  Rcpp \
  coda \
  future \
  future \
  ggmcmc \
  logging \
  loggit \
  promises \
  rstan \
  shiny \
  shinydashboard \
  tidybayes

COPY rstudio-prefs.json /etc/rstudio/rstudio-prefs.json
